### Logistic Regression

The last time we were looking linear regression, that it worked well for predicting continous outputs The idea is that linear regression does not fare well/work with classification problems.

If a problem is non-linear in nature, we will have to use logistic regression.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("import our libraries!")

import our libraries!


In [2]:
#titantic dataset

url = "http://bit.ly/wkspdata"
df = pd.read_csv(url)
df.head()

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   name      891 non-null    object 
 3   sex       891 non-null    object 
 4   age       714 non-null    float64
 5   sibsp     891 non-null    int64  
 6   parch     891 non-null    int64  
 7   ticket    891 non-null    object 
 8   fare      891 non-null    float64
 9   cabin     204 non-null    object 
 10  embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB


### Data Pre-processing

In [4]:
#drop some columns - cabin, name, ticket

dropcols = ["cabin", "name", "ticket"]
#drop the cols
#axis = 1 means cols, 0 means row
df = df.drop(dropcols, axis=1)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [6]:
#drop null values
df = df.dropna()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  712 non-null    int64  
 1   pclass    712 non-null    int64  
 2   sex       712 non-null    object 
 3   age       712 non-null    float64
 4   sibsp     712 non-null    int64  
 5   parch     712 non-null    int64  
 6   fare      712 non-null    float64
 7   embarked  712 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 50.1+ KB


In [8]:
#pclass, sex and embarked are categorical features => we need to convert them to numeric

cat_features = ["pclass", "sex", "embarked"]
df = pd.get_dummies(df, columns=cat_features)
df

survived   age  sibsp  parch     fare  pclass_1  pclass_2  pclass_3  \
0           0  22.0      1      0   7.2500         0         0         1   
1           1  38.0      1      0  71.2833         1         0         0   
2           1  26.0      0      0   7.9250         0         0         1   
3           1  35.0      1      0  53.1000         1         0         0   
4           0  35.0      0      0   8.0500         0         0         1   
..        ...   ...    ...    ...      ...       ...       ...       ...   
885         0  39.0      0      5  29.1250         0         0         1   
886         0  27.0      0      0  13.0000         0         1         0   
887         1  19.0      0      0  30.0000         1         0         0   
889         1  26.0      0      0  30.0000         1         0         0   
890         0  32.0      0      0   7.7500         0         0         1   

     sex_female  sex_male  embarked_C  embarked_Q  embarked_S  
0             0         1           0           0           1  
1             1         0           1           0           0  
2             1         0           0           0           1  
3             1         0           0           0           1  
4             0         1           0           0           1  
..          ...       ...         ...         ...         ...  
885           1         0           0           1           0  
886           0         1           0           0           1  
887           1         0           0           0           1  
889           0         1           1           0           0  
890           0         1           0           1           0  

[712 rows x 13 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   survived    712 non-null    int64  
 1   age         712 non-null    float64
 2   sibsp       712 non-null    int64  
 3   parch       712 non-null    int64  
 4   fare        712 non-null    float64
 5   pclass_1    712 non-null    uint8  
 6   pclass_2    712 non-null    uint8  
 7   pclass_3    712 non-null    uint8  
 8   sex_female  712 non-null    uint8  
 9   sex_male    712 non-null    uint8  
 10  embarked_C  712 non-null    uint8  
 11  embarked_Q  712 non-null    uint8  
 12  embarked_S  712 non-null    uint8  
dtypes: float64(2), int64(3), uint8(8)
memory usage: 38.9 KB


#### Split our data for logistic regression

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
#get our input and our output
#X and y

X = df.iloc[:, 1:]
y = df.iloc[:,0]

In [12]:
X

age  sibsp  parch     fare  pclass_1  pclass_2  pclass_3  sex_female  \
0    22.0      1      0   7.2500         0         0         1           0   
1    38.0      1      0  71.2833         1         0         0           1   
2    26.0      0      0   7.9250         0         0         1           1   
3    35.0      1      0  53.1000         1         0         0           1   
4    35.0      0      0   8.0500         0         0         1           0   
..    ...    ...    ...      ...       ...       ...       ...         ...   
885  39.0      0      5  29.1250         0         0         1           1   
886  27.0      0      0  13.0000         0         1         0           0   
887  19.0      0      0  30.0000         1         0         0           1   
889  26.0      0      0  30.0000         1         0         0           0   
890  32.0      0      0   7.7500         0         0         1           0   

     sex_male  embarked_C  embarked_Q  embarked_S  
0           1           0           0           1  
1           0           1           0           0  
2           0           0           0           1  
3           0           0           0           1  
4           1           0           0           1  
..        ...         ...         ...         ...  
885         0           0           1           0  
886         1           0           0           1  
887         0           0           0           1  
889         1           1           0           0  
890         1           0           1           0  

[712 rows x 12 columns]

In [13]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: survived, Length: 712, dtype: int64

In [14]:
#train 70% and test 30%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [15]:
from sklearn.linear_model import LogisticRegression#Step 1: import Logistic regression
log_reg = LogisticRegression(solver="newton-cg")#Step 2: initialise our model
log_reg.fit(X_train, y_train)#Step 3: train our model

print("Training complete!")

Training complete!


#### Prediction from model

In [16]:
y_pred = log_reg.predict(X_test)#Step 4: obtain model predictions
print(y_pred)

[0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1
 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1
 0 0 1 0 1 0 0 1 0 1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 1
 1 1 1 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 0 1 0]


In [17]:
df1 = pd.DataFrame({"Original Survived":y_test, "Prediction" : y_pred})
df1

Original Survived  Prediction
221                  0           0
668                  0           0
307                  1           1
570                  1           0
212                  0           0
..                 ...         ...
434                  0           0
610                  0           0
482                  0           0
404                  0           1
514                  0           0

[214 rows x 2 columns]

### Model Evaluation
We ae going to take a look at our performance metrics

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

test_acc = accuracy_score(y_test, y_pred)#Step 5: model evaluation
print("Accuracy of :", str(test_acc))

Accuracy of : 0.7990654205607477


In [19]:
## Lets take a Look at confusion matrix
confusion_matrix(y_test, y_pred)

array([[113,  16],
       [ 27,  58]], dtype=int64)

In [20]:
#precision score
test_precusion = precision_score(y_test, y_pred)
print("Accuracy of :", str(test_precusion))

Accuracy of : 0.7837837837837838


In [21]:
#recall score
test_recall = recall_score(y_test, y_pred)
print("Precision of :", str(test_recall))

Precision of : 0.6823529411764706


### Exercise: Perform Logistic Regression on the iris dataset!
- This is your y labels
    $$$$$iris = datasets.load_iris()
        ===iris_target=iris.target #this is your y!

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

print("imported our libriaies!")

imported our libriaies!


In [23]:
#Load our iris dataset
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

iris_target = iris.target #this is your y!

In [24]:
iris_target #iris sentosa, iris versicolor, iris virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
idf = iris_df.copy()
idf["Iris_class"] = iris_target
idf.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Iris_class  
0           0  
1           0  
2           0  
3           0  
4           0

In [26]:
#process our data - split our data into train test split
from sklearn.model_selection import train_test_split

#train 70% and test 30%
X_train, X_test, y_train, y_test = train_test_split(iris_df, iris_target, test_size=0.3)

### Peform logsitic regression

In [27]:
from sklearn.linear_model import LogisticRegression#Step 1: import Logistic regression
log_reg = LogisticRegression(solver="newton-cg")#Step 2: initialise our model
log_reg.fit(X_train, y_train)#Step 3: train our model

print("Training complete!")

Training complete!


In [28]:
y_pred = log_reg.predict(X_test)#Step 4: obtain model predictions
print(y_pred)

[0 0 1 1 1 2 1 1 0 1 0 2 1 1 2 1 1 0 0 1 0 2 0 1 1 1 1 0 2 2 2 2 2 1 0 1 0
 1 1 2 0 2 0 2 2]


In [29]:
df1 = pd.DataFrame({"Original":y_test, "Prediction" : y_pred})
df1

Original  Prediction
0          0           0
1          0           0
2          1           1
3          1           1
4          1           1
5          2           2
6          1           1
7          1           1
8          0           0
9          1           1
10         0           0
11         2           2
12         1           1
13         1           1
14         2           2
15         1           1
16         1           1
17         0           0
18         0           0
19         1           1
20         0           0
21         2           2
22         0           0
23         1           1
24         1           1
25         1           1
26         1           1
27         0           0
28         2           2
29         2           2
30         2           2
31         2           2
32         2           2
33         1           1
34         0           0
35         1           1
36         0           0
37         1           1
38         1           1
39         2           2
40         0           0
41         2           2
42         0           0
43         1           2
44         1           2

### Model Evaluation

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

test_acc = accuracy_score(y_test, y_pred)#Step 5: model evaluation
print("Accuracy of :", str(test_acc))

Accuracy of : 0.9555555555555556


In [31]:
## Lets take a Look at confusion matrix
confusion_matrix(y_test, y_pred)

array([[13,  0,  0],
       [ 0, 19,  2],
       [ 0,  0, 11]], dtype=int64)

In [32]:
#precision score
test_precusion = precision_score(y_test, y_pred, average=None)
print("Accuracy of :", str(test_precusion))

Accuracy of : [1.         1.         0.84615385]


In [33]:
#recall score
test_recall = recall_score(y_test, y_pred, average=None)
print("Precision of :", str(test_recall))

Precision of : [1.        0.9047619 1.       ]
